name: RADEYsanger
favicon: null
layout_spectrum: 0.15790847316384315
typography_spectrum: 0.1401601331308484
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9836083978880197
  lightness: 0.288885653950274
  saturation: 0.7660942308139056
  rhythmicContrast: 0.5517094042152166
purpose: []
